src/main/java/goojeans/harulog/post/domain/dto/PostResponseDto.java

GJNS-40[post] Response에 categoryName 추가

---

src/main/java/goojeans/harulog/post/domain/dto/PostResponseDto.java

게시글 상세보기에서 response에 user profileImg 추가

GJNS-40[Post] response에 user profileImg 추가

---

src/main/java/goojeans/harulog/user/domain/dto/KakaoOAuthAttribute.java
src/main/java/goojeans/harulog/user/service/CustomOAuth2UserService.java

[추가 사항]
- KakaoOAuthAttribute에서 password encoder 없어서 오류 발생 해결
- 불필요한 import 삭제

GJNS-94 [인코더 생성] 패스워드 인코더 오류 이슈

---

src/main/java/goojeans/harulog/comment/controller/CommentController.java
src/main/java/goojeans/harulog/comment/domain/dto/CommentResponseDto.java
src/main/java/goojeans/harulog/comment/service/CommentService.java

controller Response 추가
comment기능에서 response에 user profileImg 추가

GJNS-64[Comment] 수정

---

src/main/java/goojeans/harulog/domain/ResponseCode.java
src/main/java/goojeans/harulog/likes/controller/LikesController.java
src/main/java/goojeans/harulog/likes/domain/dto/LikesResponseDto.java
src/main/java/goojeans/harulog/likes/service/LikesService.java
src/main/java/goojeans/harulog/post/controller/PostController.java

좋아요 했을때, 취소했을때 response에 좋아요 수 출력

GJNS-55[Like] response에 좋아요 수 출력

---

src/main/java/goojeans/harulog/likes/repository/LikesRepository.java
src/main/java/goojeans/harulog/post/controller/PostController.java
src/main/java/goojeans/harulog/post/domain/dto/PostLikeResponseDto.java
src/main/java/goojeans/harulog/post/service/PostService.java

게시글 상세보기에서 유저가 좋아요 눌렀는지 여부 판단 추가

GJNS-40[post] 유저가 좋아요 눌렀는지 여부 판단 추가

---

src/main/java/goojeans/harulog/admin/service/AdminServiceImpl.java
src/main/java/goojeans/harulog/config/SecurityConfig.java
src/main/java/goojeans/harulog/filter/JwtAuthenticationFilter.java
src/main/java/goojeans/harulog/user/domain/dto/response/LoginSuccessResponse.java
src/main/java/goojeans/harulog/user/util/LoginSuccessHandler.java
src/main/java/goojeans/harulog/user/util/OAuthLoginSuccessHandler.java
src/main/resources/application-dev.yaml
src/test/resources/application-prod.yaml

[변경 사항]
- cookie samesite 옵션 제거
- 로그인 시 response data에 닉네임 및 유저 역할 반환
- 소셜 로그인 및 일반 로그인 둘 다

GJNS-96 [로그인 요청사항] 로그인 시 유저 role 및 닉네임 반환

---

src/main/java/goojeans/harulog/user/domain/dto/response/MyPageInfoResponse.java
src/main/java/goojeans/harulog/user/service/UserServiceImpl.java
src/test/java/goojeans/harulog/user/service/UserServiceTest.java

[변경 사항]
- user service에서 mypage 조회 로직 변경
- 팔로워 조회 후 존재하면 true
- MyPageInfoResponse 에 following 필드 추가
- 그에 따른 테스트 코드 로직 변경

GJNS-96 [팔로잉 확인 요청사항] 팔로잉 중인지 확인 여부 요청사항 반영

---

src/main/java/goojeans/harulog/comment/controller/CommentController.java

GJNS-64[comment] uri 수정

---

src/main/java/goojeans/harulog/user/service/UserServiceImpl.java
src/main/resources/application-ops.yaml
src/main/resources/application-test.yaml

[수정 사항]
- 전화번호 부분에 소개 삽입 부분 수정

GJNS-96 [전화번호 변경] 오타 변경

---

src/main/java/goojeans/harulog/challenge/controller/ChallengeController.java
src/main/java/goojeans/harulog/challenge/service/ChallengeService.java
src/main/java/goojeans/harulog/challenge/service/ChallengeServiceImpl.java

[변경 사항]
- 기능 추가에 따른 서비스, 컨트롤러 수정

GJNS-88 [챌린지] 다른 사용자가 참여 중인 챌린지 조회 기능 추가

---

.github/workflows/java-build.yaml
src/main/java/goojeans/harulog/config/FirebaseConfig.java
src/main/java/goojeans/harulog/user/service/UserServiceImpl.java
src/main/resources/application-firebase.yaml
src/test/resources/application-firebase.yaml

[변경 사항]
- 파이어베이스 버킷 이름 환경변수화
- 디폴트 유저 이미지 경로 변경

GJNS-96 [파이어베이스 환경변수화] 파이어베이스 버킷 이름 환경변수 설정 및 디폴트 이미지 경로 변경

---

src/main/java/goojeans/harulog/post/controller/PostStatisticController.java
src/main/java/goojeans/harulog/post/service/PostStatisticService.java
src/main/java/goojeans/harulog/post/service/PostStatisticServiceImpl.java

[변경 사항]
- 다른 유저 프로필에서 자신의 잔디밭이 뜨는 오류 수정

GJNS-88 [챌린지] 다른 유저 잔디밭 조회 추가

---

src/main/java/goojeans/harulog/post/controller/PostController.java
src/main/java/goojeans/harulog/post/domain/entity/Post.java
src/main/java/goojeans/harulog/post/service/PostService.java

GJNS-40[post] feed 이미지 등록

---

src/main/java/goojeans/harulog/user/util/OAuthLoginSuccessHandler.java

[변경 사항]
- response에 jwt 토큰, 닉네임, 유저 역할 담지 않음
- request param으로 넘김
- 그에 따른 코드 삭제

GJNS-96 [소셜 로그인 리다이렉션] 소셜 로그인 관련 리다이렉션 설정 변경

---

src/main/java/goojeans/harulog/user/util/OAuthLoginSuccessHandler.java

[변경 사항]
- Url 인코딩 오류 해결
- 한글이 포함되는 이슈로 인해 UTF-8 인코딩

GJNS-96 [Url 인코딩 오류] Url 파라미터 인코딩 오류 해결 

---

src/main/java/goojeans/harulog/user/util/OAuthLoginSuccessHandler.java

[변경 사항]
- 필요한 nickname 부분만 인코딩

GJNS-96 [인코딩 문제 해결] url 인코딩 문제 해결

---

src/main/java/goojeans/harulog/user/service/CustomOAuth2UserService.java

[추가 사항]
- 소셜 로그인 시 회원가입 시 카테고리 자동 생성

GJNS-96 [소셜 로그인 시 카테고리 생성] 소셜 로그인 오류

---

src/main/java/goojeans/harulog/domain/ResponseCode.java
src/main/java/goojeans/harulog/post/domain/entity/Post.java
src/main/java/goojeans/harulog/post/service/PostService.java

GJNS-40[post]

---

src/main/java/goojeans/harulog/config/WebSocketConfig.java
src/main/java/goojeans/harulog/filter/JwtAuthenticationFilter.java

[변경사항]
- jwtFilter에 sockjs 연결하는 /ws/info 추가
- SockJs만 연결 가능하도록 웹소켓 열어두기

GJNS-93 [hotfix] sockjs 연결 허용

---

src/main/java/goojeans/harulog/config/WebSocketConfig.java
src/main/java/goojeans/harulog/filter/JwtAuthenticationFilter.java

[변경사항]
- 웹소켓 연결 주소/ws는 모두 열어두기
- test 연결 다시 닫아두기

GJNS-93 [hotfix] /ws 모두 통과

---

src/main/java/goojeans/harulog/chat/util/ChatInboundInterceptor.java

[변경사항]
- Command가 Null이 아닐 때만 로그 찍는 걸로 변경

GJNS-93 [fix] 로그 정리

---

src/main/java/goojeans/harulog/challenge/service/ChallengeServiceImpl.java
src/test/java/goojeans/harulog/challenge/service/ChallengeServiceTest.java

GJNS-96 [챌린지 이미지] 챌린지 디폴트 이미지 추가

---

src/main/java/goojeans/harulog/chat/domain/dto/MessageDTO.java

[ 변경사항 ]
- LocalDateTime 말고 String형으로 바꿔서 내려주기

GJNS-93 [fix] 메세지 DTO 수정

---

src/main/java/goojeans/harulog/filter/JwtAuthenticationFilter.java

GJNS-96 [버그 픽스] 리프레쉬 토큰 버그
